services:
  # Backend API service
  - type: web
    name: alexandrias-journal-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: alexandrias-journal-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        value: https://alexandrias-journal.onrender.com

  # Frontend static site
  - type: web
    name: alexandrias-journal
    env: static
    instance_type: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://alexandrias-journal-api.onrender.com

databases:
  - name: alexandrias-journal-db
    databaseName: alexandrias_journal
    plan: free
    user: alexandrias_journal
