"""Add answers table

Revision ID: 602a5b29023b
Revises: 3e5a9c8d1234
Create Date: 2025-02-04 20:22:56.684742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '602a5b29023b'
down_revision: Union[str, None] = '3e5a9c8d1234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('answers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('answers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('answers', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
