"""Add is_answered column to questions

Revision ID: e011fe832da1
Revises: 602a5b29023b
Create Date: 2025-02-04 21:06:18.795218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e011fe832da1'
down_revision: Union[str, None] = '602a5b29023b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_answered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_answered')
    # ### end Alembic commands ###
